services:
  - type: web
    name: social-media-api-demo
    runtime: node
    rootDir: api
    buildCommand: npm install
    startCommand: npm run prod
    plan: free
    branch: main
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
